import React from "react";
import{ArrowUpRight,ShieldCheck}from"lucide-react";

export default function LoginView({login,setLogin,onSubmit,error,locale,setLocale}){
 const t={
  "pt-BR":{secure:"CONSOLE SEGURO",title:"Conheça sua superfície.",accent:"Reduza sua exposição.",desc:"Inteligência de exposição externa com evidência, contexto e ação.",email:"E-mail",password:"Senha",enter:"Entrar na plataforma",foot:"Isolamento por tenant · RBAC · trilha de auditoria",score:"EVIDÊNCIA PRIMEIRO",posture:"dados observados · sem score fictício",languageLabel:"Idioma"},
  en:{secure:"SECURE CONSOLE",title:"Know your surface.",accent:"Reduce your exposure.",desc:"External exposure intelligence with evidence, context and action.",email:"Email",password:"Password",enter:"Enter platform",foot:"Tenant isolation · RBAC · audit trail",score:"EVIDENCE FIRST",posture:"observed data · no fictional score",languageLabel:"Language"},
  es:{secure:"CONSOLA SEGURA",title:"Conoce tu superficie.",accent:"Reduce tu exposición.",desc:"Inteligencia de exposición externa con evidencia, contexto y acción.",email:"Correo",password:"Contraseña",enter:"Entrar a la plataforma",foot:"Aislamiento por tenant · RBAC · trazabilidad",score:"EVIDENCIA PRIMERO",posture:"datos observados · sin score ficticio",languageLabel:"Idioma"}
 }[locale]||{};
 return <div className="login-page"><div className="login-glow"/><div className="login-panel"><div className="login-brand"><div className="panther big"><img src="/assets/bsa-panther.svg" alt="Be Safe"/></div><div><b>BE SAFE</b><span>ATTACK SURFACE MANAGEMENT</span></div></div><div className="login-language"><select className="locale-select" value={locale} onChange={e=>setLocale(e.target.value)} aria-label={t.languageLabel}><option value="pt-BR">PT</option><option value="en">EN</option><option value="es">ES</option></select></div><div className="eyebrow">{t.secure}</div><h1>{t.title}<br/><i>{t.accent}</i></h1><p>{t.desc}</p><form onSubmit={onSubmit}><label>{t.email}<input type="email" autoComplete="email" required value={login.email} onChange={e=>setLogin({...login,email:e.target.value})} placeholder="you@company.com"/></label><label>{t.password}<input type="password" autoComplete="current-password" required value={login.password} onChange={e=>setLogin({...login,password:e.target.value})} placeholder="••••••••••••"/></label>{error&&<div className="error">{error}</div>}<button className="primary wide">{t.enter} <ArrowUpRight size={17}/></button></form><small>{t.foot}</small></div><div className="login-art"><div className="radar"><span/><span/><span/><span/></div><div className="art-card login-evidence-card"><div className="eyebrow">{t.score}</div><strong><ShieldCheck size={30}/></strong><span>{t.posture}</span></div></div></div>;
}
