from __future__ import annotations

from collections.abc import Iterable, Sequence
from typing import Protocol, runtime_checkable

from ...models import Asset, Finding


@runtime_checkable
class AssetFindingRepositoryPort(Protocol):
    """Application-facing contract for asset/finding persistence."""

    def all_assets(self) -> Sequence[Asset]: ...
    def all_findings(self) -> Sequence[Finding]: ...
    def list_assets(self, tenant_id: str) -> Sequence[Asset]: ...
    def list_findings(
        self,
        tenant_id: str,
        asset_ids: Iterable[str] | None = None,
    ) -> Sequence[Finding]: ...
    def find_asset_by_value(self, tenant_id: str, value: str) -> Asset | None: ...
    def find_finding(self, tenant_id: str, finding_id: str) -> Finding | None: ...
    def add_asset(self, asset: Asset) -> Asset: ...
    def add_finding(self, finding: Finding) -> Finding: ...
    def persist(self) -> None: ...
