import React,{useEffect,useMemo,useState} from "react";
import{Search,ShieldCheck,Globe2,Activity,AlertTriangle,Boxes,Waypoints,Clock3,ChevronRight,RefreshCw,LogOut,Command,Menu,X,Plus,UserRound,Layers3,BrainCircuit,ArrowUpRight,LockKeyhole,Eye,CheckCircle2,PanelLeftClose}from"lucide-react";
import{AreaChart,Area,ResponsiveContainer,Tooltip,XAxis,YAxis,CartesianGrid,BarChart,Bar}from"recharts";

const api="";
const cx=(...x)=>x.filter(Boolean).join(" ");
const esc=(v)=>String(v??"");
async function req(path,opts={}){
 const h=new Headers(opts.headers||{});const t=sessionStorage.getItem("bsa_token");if(t)h.set("Authorization","Bearer "+t);
 const r=await fetch(api+path,{...opts,headers:h});if(r.status===401){sessionStorage.removeItem("bsa_token");location.reload()}return r;
}
function App(){
 const[token,setToken]=useState(sessionStorage.getItem("bsa_token"));
 const[me,setMe]=useState(null),[dash,setDash]=useState(null),[assets,setAssets]=useState([]),[exposure,setExposure]=useState([]),[ctem,setCtem]=useState([]),[impact,setImpact]=useState([]),[story,setStory]=useState([]),[selected,setSelected]=useState(null),[search,setSearch]=useState(""),[active,setActive]=useState("overview"),[loading,setLoading]=useState(false),[sidebar,setSidebar]=useState(true),[target,setTarget]=useState(""),[discovery,setDiscovery]=useState(null),[question,setQuestion]=useState(""),[copilot,setCopilot]=useState(null),[login,setLogin]=useState({email:"",password:""}),[loginError,setLoginError]=useState("");
 const load=async()=>{setLoading(true);try{const [m,d,a,e,c,b,s]=await Promise.all([req("/api/v1/auth/me"),req("/api/v1/dashboard"),req("/api/v1/radar"),req("/api/v1/exposure"),req("/api/v1/exposure/ctem"),req("/api/v1/exposure/business-impact"),req("/api/v1/exposure/storyline")]);setMe(await m.json());setDash(await d.json());setAssets((await a.json()).assets||[]);setExposure(await e.json());setCtem((await c.json()).items||[]);setImpact((await b.json()).items||[]);setStory((await s.json()).events||[])}finally{setLoading(false)}};
 useEffect(()=>{if(token)load()},[token]);
 const filtered=useMemo(()=>assets.filter(a=>a.value.toLowerCase().includes(search.toLowerCase())||a.type.toLowerCase().includes(search.toLowerCase())),[assets,search]);
 const trend=useMemo(()=>{const base=dash?.exposure_score??0;return Array.from({length:7},(_,i)=>({day:"D-"+(6-i),score:Math.max(0,Math.round(base+(i-3)*2))}))},[dash]);
 const doLogin=async e=>{e.preventDefault();setLoginError("");const r=await fetch("/api/v1/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(login)});const d=await r.json();if(!r.ok)return setLoginError(d.detail||"Credenciais inválidas");sessionStorage.setItem("bsa_token",d.access_token);setToken(d.access_token)};
 const runDiscovery=async()=>{if(!target)return;setDiscovery({loading:true});const r=await req("/api/v1/discovery",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({target,checks:["dns","http","tls","ct"]})});setDiscovery(await r.json())};
 const ask=async()=>{if(!question)return;const r=await req("/api/v1/exposure/copilot?question="+encodeURIComponent(question));setCopilot(await r.json())};
 const logout=()=>{sessionStorage.removeItem("bsa_token");setToken(null)};
 if(!token)return <Login login={login} setLogin={setLogin} onSubmit={doLogin} error={loginError}/>;
 return <div className="app-shell">
  <aside className={cx("sidebar",!sidebar&&"collapsed")}><div className="side-brand"><div className="panther">🐆</div>{sidebar&&<div><b>BE SAFE</b><span>ASM / EXPOSURE</span></div>}</div>
   <nav>{[["overview","Overview",Activity],["surface","Attack Surface",Globe2],["ctem","CTEM Queue",Waypoints],["assets","Assets",Boxes],["story","Change Storyline",Clock3],["admin","Governance",Layers3]].map(([id,label,Icon])=><button key={id} className={cx("nav-item",active===id&&"active")} onClick={()=>setActive(id)}><Icon size={18}/>{sidebar&&<><span>{label}</span>{id==="ctem"&&ctem.length>0&&<em>{ctem.length}</em>}</>}</button>)}</nav>
   {sidebar&&<div className="side-bottom"><div className="tenant-card"><div className="eyebrow">TENANT</div><strong>{me?.tenant_id||"tenant-demo"}</strong><span>{me?.role||"analyst"} · protected</span></div><button className="nav-item" onClick={logout}><LogOut size={17}/>Sair</button></div>}
  </aside>
  <main className="workspace"><header className="topbar"><button className="icon-btn" onClick={()=>setSidebar(!sidebar)}>{sidebar?<PanelLeftClose size={19}/>:<Menu size={19}/>}</button><div className="crumb"><span>Be Safe ASM</span><ChevronRight size={14}/><b>{active==="overview"?"Exposure Overview":active==="surface"?"Attack Surface":active==="ctem"?"CTEM Queue":active==="assets"?"Asset Inventory":active==="story"?"Change Storyline":"Governance"}</b></div><div className="top-actions"><div className="status"><i/> LIVE INTELLIGENCE</div><button className="icon-btn" onClick={load}><RefreshCw size={17} className={loading?"spin":""}/></button><div className="avatar">{(me?.name||"M").slice(0,1).toUpperCase()}</div></div></header>
   <div className="content">
    {active==="overview"&&<Overview dash={dash} exposure={exposure} ctem={ctem} impact={impact} trend={trend} onAsset={setSelected}/>}
    {active==="surface"&&<Surface assets={assets} filtered={filtered} search={search} setSearch={setSearch} target={target} setTarget={setTarget} runDiscovery={runDiscovery} discovery={discovery} onAsset={setSelected}/>}
    {active==="assets"&&<Assets assets={filtered} search={search} setSearch={setSearch} onAsset={setSelected}/>}
    {active==="ctem"&&<CTEM items={ctem} onAsset={setSelected}/>}
    {active==="story"&&<Story events={story} onAsset={setSelected}/>}
    {active==="admin"&&<Governance me={me}/>}
    <section className="copilot"><div className="copilot-icon"><BrainCircuit size={20}/></div><div className="copilot-body"><div className="eyebrow">EXPOSURE COPILOT <span>evidence-grounded</span></div><strong>Pergunte sobre sua superfície</strong><div className="copilot-input"><input value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>e.key==="Enter"&&ask()} placeholder='“O que mudou?”  “Quais ativos estão sem owner?”  “O que está mais exposto?”'/><button onClick={ask}><Command size={16}/> Perguntar</button></div>{copilot&&<div className="copilot-answer"><b>{copilot.answer}</b><div>{(copilot.evidence||[]).slice(0,5).map(x=><span key={x.asset_id}>{x.asset} · confidence {x.confidence}</span>)}</div></div>}</div></section>
   </div>
  </main>
  {selected&&<AssetDrawer id={selected} onClose={()=>setSelected(null)}/>}
 </div>
}
function Login({login,setLogin,onSubmit,error}){return <div className="login-page"><div className="login-glow"/><div className="login-panel"><div className="login-brand"><div className="panther big">🐆</div><div><b>BE SAFE</b><span>ATTACK SURFACE MANAGEMENT</span></div></div><div className="eyebrow">SECURE CONSOLE</div><h1>Know your surface.<br/><i>Reduce your exposure.</i></h1><p>External exposure intelligence com evidência, contexto e ação.</p><form onSubmit={onSubmit}><label>E-mail<input type="email" required value={login.email} onChange={e=>setLogin({...login,email:e.target.value})} placeholder="you@company.com"/></label><label>Senha<input type="password" required value={login.password} onChange={e=>setLogin({...login,password:e.target.value})} placeholder="••••••••••••"/></label>{error&&<div className="error">{error}</div>}<button className="primary wide">Entrar na plataforma <ArrowUpRight size={17}/></button></form><small>Tenant isolation · RBAC · audit trail</small></div><div className="login-art"><div className="radar"><span/><span/><span/><span/></div><div className="art-card"><div className="eyebrow">EXPOSURE SCORE</div><strong>62</strong><span>contextual posture</span></div></div></div>}
function Overview({dash,exposure,ctem,impact,trend,onAsset}){return <><PageTitle eyebrow="EXPOSURE INTELLIGENCE" title={<>Sua superfície, <i>explicada.</i></>} sub="Uma visão operacional da exposição externa, do risco ao próximo passo."/><div className="kpis">{[["Exposure Score",dash?.exposure_score??"—","contextual"],["Assets",dash?.total_assets??"—","discovered"],["Open Findings",dash?.open_findings??"—","needs action"],["Critical",dash?.critical_findings??"—","priority"],["Changes 24h",dash?.changes_24h??"—","continuous"]].map(([l,v,s],i)=><div className={cx("kpi",i===0&&"hero-kpi")} key={l}><span>{l}</span><strong>{v}</strong><small>{s}</small></div>)}</div><div className="grid-main"><section className="panel chart-panel"><PanelHead title="Exposure posture" meta="7-day signal"/><div className="chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trend}><defs><linearGradient id="pinkFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#ff2d84" stopOpacity=".32"/><stop offset="100%" stopColor="#ff2d84" stopOpacity="0"/></linearGradient></defs><CartesianGrid stroke="#232936" vertical={false}/><XAxis dataKey="day" stroke="#687080" tickLine={false} axisLine={false}/><YAxis stroke="#687080" tickLine={false} axisLine={false}/><Tooltip contentStyle={{background:"#11151e",border:"1px solid #2b3240",borderRadius:12,color:"#fff"}}/><Area type="monotone" dataKey="score" stroke="#ff2d84" strokeWidth={3} fill="url(#pinkFill)"/></AreaChart></ResponsiveContainer></div></section><section className="panel"><PanelHead title="Top exposure" meta="risk-ranked"/><div className="rank-list">{exposure.slice(0,6).map(x=><button className="rank" key={x.asset_id} onClick={()=>onAsset(x.asset_id)}><div><strong>{x.asset}</strong><span>{x.band} · {x.rationale?.[0]||"contextual"}</span></div><b>{x.score}</b></button>)}</div></section></div><div className="grid-main lower"><section className="panel"><PanelHead title="CTEM queue" meta={ctem.length+" items"}/>{ctem.slice(0,5).map(x=><button className="row" key={x.asset_id} onClick={()=>onAsset(x.asset_id)}><div className="dot pink-dot"/><div><strong>{x.asset}</strong><span>{x.next_action} · {x.owner||"unowned"}</span></div><b>{x.priority_score}</b><ChevronRight size={16}/></button>)}</section><section className="panel"><PanelHead title="Business impact" meta="context"/>{impact.slice(0,5).map(x=><div className="row" key={x.asset_id}><div className="dot amber-dot"/><div><strong>{x.asset}</strong><span>{x.business_unit||"Unknown"} · {x.environment}</span></div><b>{x.impact_index}</b></div>)}</section></div></>}
function PageTitle({eyebrow,title,sub}){return <div className="page-title"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{sub}</p></div><div className="secure"><ShieldCheck size={16}/> Evidence-first</div></div>}
function PanelHead({title,meta}){return <div className="panel-head"><h3>{title}</h3><span>{meta}</span></div>}
function Assets({assets,search,setSearch,onAsset}){return <><PageTitle eyebrow="ASSET INVENTORY" title={<>Conheça cada <i>ativo.</i></>} sub="Inventário vivo com ownership, confidence e exposição contextual."/><div className="toolbar-pro"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar hostname, domínio, IP ou tipo..."/><span>{assets.length} ativos</span></div><div className="panel table-panel"><table><thead><tr><th>Asset</th><th>Type</th><th>Ownership</th><th>Confidence</th><th>Criticality</th><th>Exposure</th><th/></tr></thead><tbody>{assets.map(a=><tr key={a.asset_id} onClick={()=>onAsset(a.asset_id)}><td><strong>{a.value}</strong><small>{a.dna}</small></td><td><span className="tag">{a.type}</span></td><td>{a.owner||<span className="warn">Unowned</span>}</td><td><Meter value={a.confidence}/></td><td><span className="critical">{a.criticality}/5</span></td><td><span className={cx("score-pill",a.change_type!=="stable"&&"hot")}>{a.change_type==="stable"?"stable":"changed"}</span></td><td><ChevronRight size={16}/></td></tr>)}</tbody></table></div></>}
function Surface({assets,filtered,search,setSearch,target,setTarget,runDiscovery,discovery,onAsset}){return <><PageTitle eyebrow="ATTACK SURFACE" title={<>Mapeie o <i>desconhecido.</i></>} sub="Discovery controlado por escopo, com evidência e correlação."/><div className="discover-box"><div className="discover-copy"><div className="icon-orb"><Globe2/></div><div><h3>Run controlled discovery</h3><p>DNS · HTTP · TLS · Certificate Transparency</p></div></div><div className="discover-form"><input value={target} onChange={e=>setTarget(e.target.value)} placeholder="cliente.com.br"/><button className="primary" onClick={runDiscovery}><Search size={16}/> Descobrir</button></div>{discovery&&!discovery.loading&&<pre>{JSON.stringify(discovery,null,2)}</pre>}</div><Assets assets={filtered} search={search} setSearch={setSearch} onAsset={onAsset}/></>}
function CTEM({items,onAsset}){return <><PageTitle eyebrow="CONTINUOUS THREAT EXPOSURE MANAGEMENT" title={<>Da descoberta à <i>ação.</i></>} sub="Fila priorizada por exposição, criticidade, contexto e evidência."/><div className="ctem-board"><div className="stage"><div className="stage-head"><span>01</span><b>VALIDATE</b><em>{items.filter(x=>x.stage==="validate").length}</em></div>{items.filter(x=>x.stage==="validate").map(x=><CTCard x={x} onClick={()=>onAsset(x.asset_id)}/>)}</div><div className="stage hot-stage"><div className="stage-head"><span>02</span><b>REMEDIATE</b><em>{items.filter(x=>x.stage==="prioritize").length}</em></div>{items.filter(x=>x.stage==="prioritize").map(x=><CTCard x={x} onClick={()=>onAsset(x.asset_id)}/>)}</div><div className="stage"><div className="stage-head"><span>03</span><b>RETEST</b><em>—</em></div><div className="empty-stage">Nada aguardando reteste</div></div></div></>}
function CTCard({x,onClick}){return <button className="ct-card" onClick={onClick}><div className="ct-top"><span>{x.asset}</span><b>{x.priority_score}</b></div><p>{x.next_action}</p><div><span>{x.owner||"Unowned"}</span><span>Criticality {x.criticality}/5</span></div></button>}
function Story({events,onAsset}){return <><PageTitle eyebrow="CHANGE INTELLIGENCE" title={<>Conte a história da <i>exposição.</i></>} sub="Mudanças materiais com evidência e explicabilidade."/><div className="storyline">{events.length?events.map((e,i)=><div className="story-event" key={e.asset_id+"-"+i}><div className="story-time">{e.timestamp?.slice(0,16).replace("T"," ")}</div><div className="story-line"><i/></div><button className="story-card" onClick={()=>onAsset(e.asset_id)}><div className="eyebrow">{e.event}</div><h3>{e.asset}</h3><p>{e.signals.join(" · ")}</p><div className="evidence-row"><span>confidence {e.confidence}</span>{e.explainability?.map(x=><span key={x}>{x}</span>)}</div></button></div>):<div className="panel empty-stage">Nenhuma mudança material detectada.</div>}</div></>}
function Governance({me}){return <><PageTitle eyebrow="GOVERNANCE" title={<>Controle sem <i>atrito.</i></>} sub="Tenant isolation, RBAC, scopes e rastreabilidade operacional."/><div className="grid-main"><section className="panel"><PanelHead title="Identity" meta="current session"/><div className="identity"><div className="avatar large">{(me?.name||"M").slice(0,1)}</div><div><h3>{me?.name}</h3><p>{me?.email}</p><span className="tag">{me?.role}</span><span className="tag">{me?.tenant_id}</span></div></div></section><section className="panel"><PanelHead title="Security posture" meta="platform"/><div className="security-list"><div><LockKeyhole/> Tenant isolation <b>ENFORCED</b></div><div><Eye/> Scoped discovery <b>ENFORCED</b></div><div><CheckCircle2/> Audit trail <b>ACTIVE</b></div></div></section></div></>}
function Meter({value}){return <div className="meter"><i style={{width:value+"%"}}/><span>{value}%</span></div>}
function AssetDrawer({id,onClose}){const[d,setD]=useState(null);useEffect(()=>{req("/api/v1/assets/"+id).then(r=>r.json()).then(setD)},[id]);return <div className="drawer-backdrop" onClick={e=>e.target===e.currentTarget&&onClose()}><aside className="drawer">{!d?<div className="loading">Carregando Asset 360…</div>:<><div className="drawer-head"><div><div className="eyebrow">ASSET 360</div><h2>{d.asset.value}</h2><p>{d.asset.type} · {d.asset.environment} · {d.asset.status}</p></div><button className="icon-btn" onClick={onClose}><X/></button></div><div className="drawer-grid">{[["Risk",d.risk.score],["Ownership",d.ownership.score+"%"],["Blast Radius",d.blast_radius],["Evidence",d.evidence.evidence_count]].map(x=><div className="drawer-stat" key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></div>)}</div><div className="drawer-section"><PanelHead title="Why this matters" meta="explainable"/>{d.risk.rationale?.map(x=><div className="reason" key={x}><span>+</span>{x}</div>)}</div><div className="drawer-section"><PanelHead title="Findings" meta={d.findings.length}/>{d.findings.map(f=><div className="finding-row" key={f.id}><div><b>{f.title}</b><span>{f.severity} · {f.status}</span></div><strong>{f.context_score}</strong></div>)}</div><div className="drawer-section"><PanelHead title="Exposure DNA" meta="fingerprint"/><code>{d.exposure_dna?.fingerprint||"—"}</code><div className="evidence-row">{d.exposure_dna?.explainability?.map(x=><span key={x}>{x}</span>)}</div></div></>}</aside></div>}
export default App;
